//===- MtFusionStructuredOps.td - MtFusion dialect library ops -*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MTFUSION_IR_MTFUSIONSTRUCTUREDOPS
#define MTFUSION_IR_MTFUSIONSTRUCTUREDOPS

include "mtir/Dialect/MtFusion/IR/MtFusionBase.td"

#endif // MTFUSION_IR_MTFUSIONSTRUCTUREDOPS